
version: 2

models:
    - name: customers
      description: "Each customer, how many orders they have placed, and when they placed their first order."
      columns:
          - name: customer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: monthly_customers
      description: "The number of new customers by month"
      columns:
          - name: number_of_new_customers
            description: "Count of customers whose first order was in this month"
