
version: 2

models:
    - name: customers
      description: "Each customer, how many orders they have placed, and when they placed their first order."
      columns:
          - name: customer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
